<a href="https://colab.research.google.com/github/m1016m/NN/blob/master/NLP_numpy%E5%89%8D%E7%BD%AE%E6%8A%80%E8%A1%93.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#NLP numpy前置技術
#一個班級的學生學號通過一維數組表示應為 
# 索引    學號
# 0       1
# 1       2
# 2       3
# 3       4
#其中a[0] 代表學號1

#通過二維數組表示應為
# 1      Tim
# 2      Joey
# 3      Johnny
# 4      Frank
#其中b[0,0] 代表學號1,b[0 , 1] 代表的就是Tim
#以線性代數的說法，一維數組稱為向量(vector),二維數組稱為矩陣(matrix)

import numpy as np
vector = np.array([1,2,3,4])
matrix = np.array([[1,'Tim'],[2 , 'Joey'],[3 , 'Johnny'] ,[4 , 'Frank']])
print (vector)
print (matrix)

[1 2 3 4]
[['1' 'Tim']
 ['2' 'Joey']
 ['3' 'Johnny']
 ['4' 'Frank']]


In [0]:
#獲取numpy中數組的維度

a = np.arange(15).reshape(3 , 5)#代表3列5行
print('ndim :',a.ndim)
print('shape :',a.shape)
print('size :',a.size)

ndim : 2
shape : (3, 5)
size : 15


In [0]:
#獲取數據 genfromtxt()
# import numpy as np
# nfl = np.genfromtxt('u.csv' , delimiter =',')
# print(nfl)
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

# 確認 2.csv 是否已上載
!ls *.* -l

Saving u.csv to u.csv
User uploaded file "u.csv" with length 2079182 bytes
-rw-r--r-- 1 root root 2079182 Jul 30 03:18 u.csv


In [0]:
import numpy as np
nfl = np.genfromtxt('u.csv',delimiter = ',')
print(nfl)

[[0.00000000e+00 1.00000000e+00 2.00000000e+00 3.00000000e+00]
 [1.96000000e+02 2.42000000e+02 3.00000000e+00 8.81250949e+08]
 [1.86000000e+02 3.02000000e+02 3.00000000e+00 8.91717742e+08]
 ...
 [2.76000000e+02 1.09000000e+03 1.00000000e+00 8.74795795e+08]
 [1.30000000e+01 2.25000000e+02 2.00000000e+00 8.82399156e+08]
 [1.20000000e+01 2.03000000e+02 3.00000000e+00 8.79959583e+08]]


In [0]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

# 確認 2.csv 是否已上載
!ls *.* -l

Saving house-prices.csv to house-prices.csv
User uploaded file "house-prices.csv" with length 3867 bytes
-rw-r--r-- 1 root root    3867 Jul 30 03:38 house-prices.csv
-rw-r--r-- 1 root root 2079182 Jul 30 03:18 u.csv


In [0]:
import numpy as np
nfl = np.genfromtxt('house-prices.csv',delimiter = ',')
print(nfl)

[[      nan       nan       nan ...       nan       nan       nan]
 [1.000e+00 1.143e+05 1.790e+03 ... 2.000e+00       nan       nan]
 [2.000e+00 1.142e+05 2.030e+03 ... 3.000e+00       nan       nan]
 ...
 [1.260e+02 1.135e+05 2.070e+03 ... 2.000e+00       nan       nan]
 [1.270e+02 1.499e+05 2.020e+03 ... 1.000e+00       nan       nan]
 [1.280e+02 1.246e+05 2.250e+03 ... 4.000e+00       nan       nan]]


In [0]:
#Home => House id,Price => House price,Bedrooms => 有多少個臥室？,Bathroom => 有多少個洗手間？Brick => 是否是磚房？,Neighborhood => House area
#正確讀取數據,numpy數組中必須是相同資料型態的, na表示讀取的數值是空的，不存在的，nan是因為數據類型轉換出錯，對於nan的類型可用genfromtxt()轉化數據類型
#dtype設定為'U75',表示每個值都是75byte的unicode,skip_header設置為整數，這個參數可以跳過文件開頭的對應的行數，然後再執行其他的操作
import numpy as np
nfl = np.genfromtxt('house-prices.csv',dtype = 'U75' ,skip_header = 1 ,delimiter = ',')
print(nfl)

[['1' '114300' '1790' ... '2' 'No' 'East']
 ['2' '114200' '2030' ... '3' 'No' 'East']
 ['3' '114800' '1740' ... '1' 'No' 'East']
 ...
 ['126' '113500' '2070' ... '2' 'No' 'North']
 ['127' '149900' '2020' ... '1' 'No' 'West']
 ['128' '124600' '2250' ... '4' 'No' 'North']]


In [0]:
#Numpy 數組索引
import numpy as np
martix = np.array([[1 ,2 ,3] ,[10 , 20 , 30]])
print(martix[0 , 2])

3


In [0]:
#切片
import numpy as np
martix  = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(martix[:,1])#選擇所有的列，第一行 印出 20,25,30
print(martix[:,0 : 2])#選擇所有的列，行的索引是第零到一行 印出 [[ 5 10][20 25][35 40]]
print(martix[1:3,:])#選擇所有的行，列的索引是第一到二列 印出[[20 25 30][35 40 45]]
print(martix[1:3,0:2])#列的索引是第一到二列，行的索引是第零到一行 印出[[20 25][35 40]]

[10 25 40]
[[ 5 10]
 [20 25]
 [35 40]]
[[20 25 30]
 [35 40 45]]
[[20 25]
 [35 40]]


In [0]:
#數組比較產生布林值
import numpy as np
martix  = np.array([[5,10,15],[20,25,30],[35,40,45]])
m = (martix == 25)
print(m)

[[False False False]
 [False  True False]
 [False False False]]


In [0]:
#下載檔案
from google.colab import files
files.download('movie_ratings.csv')

In [4]:
#較複雜的範例
import numpy as np
martix  = np.array([[5,10,15],[20,25,30],[35,40,45]])
second_column_25 = (martix[:,1] == 25)#所有的列第一行
print(second_column_25)
print(martix[second_column_25,:])#second_column_25的那一行全部

#多個條件
vector = np.array([5,10,11,12])
equalto_five_and_ten = (vector == 5) & (vector == 10)
print(equalto_five_and_ten)

equalto_five_or_ten = (vector == 5) | (vector == 10)
print(equalto_five_or_ten)

[False  True False]
[[20 25 30]]
[False False False False]
[ True  True False False]


In [5]:
#在數組中
import numpy as np
vector = np.array([5,10,11,12])
equalto_ten_or_five = (vector == 10) & (vector == 5)
vector[equalto_ten_or_five] = 50#表示值如果是10 or 5的話都會變成50
print(vector)

#在矩陣中
martix  = np.array([[5,10,15],[20,25,30],[35,40,45]])
second_column_25 = (martix[:,1] == 25)#所有的列第一行
martix[second_column_25,1] = 10
print(martix)

[ 5 10 11 12]
[[ 5 10 15]
 [20 10 30]
 [35 40 45]]


In [7]:
#替換空值
import numpy as np
martix  = np.array([['5','10','15'],['20','25','30'],['35','40','']])
second_column_25 = (martix[:,:] == '')
martix[second_column_25] = '0'
print(martix)

[['5' '10' '15']
 ['20' '25' '30']
 ['35' '40' '0']]


In [11]:
#Numpy的統計計算方法
import numpy as np
vector = np.array([10,20,30,40])
print(vector.sum())

martix  = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(martix.sum(axis = 1))#沿列相加
print(martix.sum(axis = 0))#沿欄相加

100
[ 30  75 120]
[60 75 90]
